### ISSUE TITLE
Status while it's running?

### ISSUE THREAD

**Issue by ragingdave** [ijpatricio/nova-larastan-tool#1]
I'm not necessarily even saying that it would need to give a progress bar (though would be nice), can it at least have some indication that pressing the button did something?

**Comment by ijpatricio** [comment]
Nice found! Will do it! As you said, at least a spinner 👍

**Comment by ijpatricio** [comment]
Hey @ragingdave 

I just put a spinner, indicating that the ajax request is performing.

![image](https://user-images.githubusercontent.com/26031459/45356852-6e12b900-b5bc-11e8-9ad6-df73538ad045.png)

Can you please update and check if everything alright?

Thanks!

**Comment by ragingdave** [comment]
Just tested it and it for sure works, other than some parsing issues that are unrelated to this.

**Comment by ijpatricio** [comment]
Thanks!

I didn't get it. Can you elaborate on that parsing issues?

**Comment by ragingdave** [comment]
I'm not even sure if this can be handled by this, but basically if it hits an exception and can't complete the scan then it fails. Maybe if it can't parse the result it should just return whatever it has to help diagnose the issue, rather than having to rerun the artisan code:analyse command

**Comment by ijpatricio** [comment]
Thanks. Will dig deeper. 
From what you say, it's a matter of outputting the exception message and trace (same info as you get from running in console).

Is this accurate?

**Comment by ragingdave** [comment]
Pretty much.

**Comment by ijpatricio** [comment]
I'll try to open a new issue, based on this.

(My first steps on open source 😃 )

**Comment by ijpatricio** [comment]
Opened https://github.com/ijpatricio/nova-larastan-tool/issues/2#issue-359072378
I mentioned you, but I guess it didn't work as you're still not participating in that issue.

Can you go there and say something, so I can close this one and keep issues organized?

Thanks!
