### ISSUE TITLE
Output response if server error on ajax

### ISSUE THREAD

**Issue by ijpatricio** [ijpatricio/nova-larastan-tool#2]
https://github.com/ijpatricio/nova-larastan-tool/issues/1#issuecomment-420290186

@ragingdave

> I'm not even sure if this can be handled by this, but basically if it hits an exception and can't complete the scan then it fails. Maybe if it can't parse the result it should just return whatever it has to help diagnose the issue, rather than having to rerun the artisan code:analyse command

**Comment by ragingdave** [comment]
hello!

**Comment by ijpatricio** [comment]
Hey @ragingdave :)

It's not the most pretty, but hey, it works, right?

![image](https://user-images.githubusercontent.com/26031459/45394158-3725bd00-b627-11e8-8562-2a1ee1957e57.png)

If you can please check, that would be awesome, thanks!

**Comment by ragingdave** [comment]
I checked this out this morning but unfortunately, while I get an error message, I end up getting this:
```
Holy smokes! Something seriously bad happened.
Exception: Symfony\Component\HttpKernel\Exception\HttpException
File: /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php
Line: 941
Message: Error decoding output from code:analyse command
```
in the UI, which while slightly more helpful, still has me running the command again in the cli to figure out what really went wrong. perhaps throwing the same exception but with the artisan output as the message in CodeAnalyseService:processReportOutput()?

**Comment by ijpatricio** [comment]
Nice, one. Done.

Is it OK now? Can you point me how to reproduce it?

**Comment by ragingdave** [comment]
Unfortunately I eliminated the code errors that was causing that....I'm calling it good from last I had one.

**Comment by ijpatricio** [comment]
@ragingdave no problem. So it seems solved for now, I'll close the issue.

Thank you for your contribution ❤️
